### ISSUE TITLE
bold & regular fonts

### ISSUE THREAD

**Issue by sorawee** [mbutterick/quad#56]
I'm trying to get the font `Sarabun` working with quad. I downloaded the font from https://fonts.google.com/specimen/Sarabun and, per the instruction, rename `Sarabun-Bold.ttf` to `bold.tff` and `Sarabun-Regular.ttf` to `regular.ttf`. Yet, quad always prefers the bold variant. It's only when I delete `bold.ttf` that the regular variant is used. (I tried setting `font-bold` to `"false"` explicitly, but that doesn't help).

Besides this, I have two more questions:

- Is it possible to detect names like `Sarabun-Regular.ttf` automatically? As I understand, most TTF files are named using this convention rather than plain `regular.ttf`, etc.
- Sarabun also comes with the `ExtraBold`, `ExtraLight`, `Light`, `Medium`, `Thin`, and `SemiBold` variants. Will quad ever support these?

**Comment by mbutterick** [comment]
What matters is not the font names but the directory names. So `fonts/sarabun/regular` would contain the regular style, `fonts/sarabun/bold` the bold style, and so on. The file names of the fonts themselves don’t matter. 

As for supporting other weights, I think the right direction would be to support CSS-style weight integers (100 to 900 inclusive, I think). Style names like `ExtraBold` and `SemiBold` have no canonical meaning. Then you would set up subdirectories with those numbers, I suppose.

Think of the `fonts` subdirectory system as analogous to `@font-face` declarations in CSS.* We want to have a way of mapping font files onto certain semantics without depending on parsing anything in the font itself, including its name, because a) all of that could be lies and b) it’s more flexible to keep them separate. For instance, you can drop any weight you want into the `bold` subdirectory, and it gets used as the bold style. 

* I could’ve had a config file with font declarations, but then there needs to be a new format and parsing and blah blah. Whereas moving files around the filesystem is simple and concrete.

**Comment by sorawee** [comment]
Ah, I thought that I need "fonts/Sarabun/bold.ttf", but in fact I need "fonts/Sarabun/bold/whatever-name.ttf", correct?

The question then is, why is the current way  (three levels) better than the incorrect way that I did (two levels). Will there ever be the case that the sub-subdirectory has more than one TTF in the current scheme?

**Comment by mbutterick** [comment]
I consider the filename of a font to be essential to the font in a way that its containing directory is not. For instance, a family like Sarabun has multiple weights heavier than regular. Any of which you might want to use as the bold style. If you have to change its name to `bold.ttf`, now you can’t see which style you’re using as the bold. (Again, consider the analogy to `@font-face`, which doesn’t make you change the name of any font file.) So the advantage of this approach is that it preserves information that the author might like to know.

> Will there ever be the case that the sub-subdirectory has more than one TTF in the current scheme?

I can’t foresee what that situation would be, though maybe it will become apparent.

**Comment by mbutterick** [comment]
(FWIW part of the intent of this system is to be approachable to writers who are not necessarily technically oriented. Font mapping is an annoying chore, but everyone gets how directories work.)

**Comment by sorawee** [comment]
I understand the rationale now. Still not sure if this is the best interface, but I'll live with it for now.

**Comment by mbutterick** [comment]
> Still not sure if this is the best interface

Neither am I, but I haven’t come up with a better idea :wink: If you do, I’m open to persuasion.
